name: Docker Build & Push

on:
  push:
    branches: [main]
    paths:
      - 'containers/prod/Dockerfile'
      - 'app/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -f containers/prod/Dockerfile -t airflow-prod .
      # Add ECR login/push steps as needed
