name: Terraform Plan & Apply

on:
  pull_request:
    paths:
      - 'infra/**'
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Format
        run: terraform -chdir=infra fmt -recursive
      - name: Terraform Validate
        run: terraform -chdir=infra validate
      - name: Terraform Plan
        run: terraform -chdir=infra plan
